# Generated by Django 4.2.6 on 2023-10-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tech_speciality_alter_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True, verbose_name='Ticket Update')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='history',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ticket_history', verbose_name='Ticket History'),
        ),
    ]
