# Generated by Django 4.2.6 on 2023-10-29 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ticket_history_ticket_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='history',
            field=models.ForeignKey(auto_created=True, blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ticket_history', verbose_name='Ticket History'),
        ),
    ]
