# Generated by Django 4.2.6 on 2023-10-29 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_ticket_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criticy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50, verbose_name='level')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='history',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tech', verbose_name='Tech'),
        ),
        migrations.DeleteModel(
            name='Ticket_History',
        ),
        migrations.AddField(
            model_name='ticket',
            name='criticy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.criticy', verbose_name='Criticy'),
        ),
    ]
