# Generated by Django 4.2.6 on 2023-10-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_history_ticket_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='history',
            field=models.ManyToManyField(blank=True, to='core.history'),
        ),
    ]
