# Generated by Django 4.2.6 on 2023-11-10 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_alter_ticket_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='speciality',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='history',
        ),
        migrations.AddField(
            model_name='tech',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Speciality',
        ),
    ]
